"""Stable public facade for schematic geometry review."""

from .schematic_geometry_scan import scan_unconnected_pin_wire_geometry, scan_wire_ends_on_pin_lines
from .schematic_geometry_source import resolve_schematic_sheet_path, schematic_sheet_references
from .schematic_geometry_tree import scan_schematic_geometry_tree
from .schematic_geometry_types import (
    DISTANCE_COMPARISON_EPSILON_MM,
    MAX_LABEL_ENDPOINT_GAP_MM,
    MAX_PIN_ENDPOINT_GAP_MM,
    MAX_SHEET_OCCURRENCES,
    POINT_TOLERANCE_MM,
    SUPPORTED_KICAD_VERSION,
    SUPPORTED_KICAD_VERSIONS,
    SUPPORTED_SCHEMATIC_VERSION,
    CoincidentTextAnchors,
    FreeTextOverlap,
    FreeTextSymbolBodyOverlap,
    FreeTextWireOverlap,
    LabelNearWireEndpoint,
    LabelWireEndpointCandidate,
    PinTipOnWireInterior,
    SchematicGeometryScan,
    SchematicSheetReference,
    SchematicSourceBinding,
    UnmarkedTJunction,
    UnmarkedWireCrossing,
    WireEndOnPinLine,
    WireEndpointNearPinTip,
    WireThroughSymbolBody,
)

__all__ = [
    "DISTANCE_COMPARISON_EPSILON_MM",
    "MAX_LABEL_ENDPOINT_GAP_MM",
    "MAX_PIN_ENDPOINT_GAP_MM",
    "MAX_SHEET_OCCURRENCES",
    "POINT_TOLERANCE_MM",
    "SUPPORTED_KICAD_VERSION",
    "SUPPORTED_KICAD_VERSIONS",
    "SUPPORTED_SCHEMATIC_VERSION",
    "CoincidentTextAnchors",
    "FreeTextOverlap",
    "FreeTextSymbolBodyOverlap",
    "FreeTextWireOverlap",
    "LabelNearWireEndpoint",
    "LabelWireEndpointCandidate",
    "PinTipOnWireInterior",
    "SchematicGeometryScan",
    "SchematicSheetReference",
    "SchematicSourceBinding",
    "UnmarkedTJunction",
    "UnmarkedWireCrossing",
    "WireEndOnPinLine",
    "WireEndpointNearPinTip",
    "WireThroughSymbolBody",
    "resolve_schematic_sheet_path",
    "scan_schematic_geometry_tree",
    "scan_unconnected_pin_wire_geometry",
    "scan_wire_ends_on_pin_lines",
    "schematic_sheet_references",
]
